# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Mind press :: concept
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow
    viewport: 'width=device-width,initial-scale=1'

  stylesheets:
    - normalize.css
    - common.css
    - //api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.css
    - //cdnjs.cloudflare.com/ajax/libs/select2/3.5.2/select2.min.css

  javascripts:
    - //cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js
    - //api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.js
    - //cdnjs.cloudflare.com/ajax/libs/select2/3.5.2/select2.min.js
    - http://code.highcharts.com/highcharts.js
    - http://code.highcharts.com/highcharts-more.js
    - http://code.highcharts.com/modules/exporting.js
  has_layout:     true
  layout:         layout
